### ISSUE TITLE
HelloResource example- webclient should be closed

### ISSUE THREAD

**Issue by fiorenzino** [FroMage/redpipe#10]
if i'm right, you should close the webclient after use:

    private Single<String> get(Vertx vertx, URI uri) {
        WebClient client = WebClient.create(vertx);
        Single<HttpResponse<Buffer>> responseHandler =
                client.get(uri.getPort(), uri.getHost(), uri.getPath()).rxSend();

        return responseHandler.map(response -> response.body().toString())
                .doAfterTerminate(
                        () -> {
                            client.close();
                        }
                );
    }

**Comment by FroMage** [comment]
that sounds correct, thanks.

**Comment by FroMage** [comment]
Fixed, thanks.
