### ISSUE TITLE
Server start method - why don't use conf/config.json?

### ISSUE THREAD

**Issue by fiorenzino** [FroMage/redpipe#11]
Reading the net.redpipe.engine.core.Server code, the vertx instance is always started using no options:

VertxOptions options = new VertxOptions();
options.setWarningExceptionTime(9223372036854775807L);
this.vertx = Vertx.vertx(options);

We could use the "conf/config.json" properties to init vertx:
VertxOptions vertxOptions = new VertxOptions(jsonObject);

and like said VertxOptionsConverter.fromJson, we can configure all the vertx options:
addressResolverOptions,
blockedThreadCheckInterval,
clusterHost,
clusterPingInterval,
clusterPingReplyInterval,
clusterPort,
clusterPublicHost,
clusterPublicPort,
clustered,
eventBusOptions,
eventLoopPoolSize,
fileResolverCachingEnabled,
haEnabled,
haGroup,
internalBlockingPoolSize,
maxEventLoopExecuteTime,
maxWorkerExecuteTime,
metricsOptions,
preferNativeTransport,
quorumSize,
warningExceptionTime,
workerPoolSize

**Comment by FroMage** [comment]
Very good idea!

**Comment by FroMage** [comment]
Sorry I can't really check the diff because you changed indentation, so I'm not sure what changes you made.

I think the `conf/config.json` should be resolved in the CWD of the current application, not in the root project. That's what makes the most sense.

Otherwise  `Starter` is deprecated, and seems to be a `main` entry point, which is not going to work for us, no?

**Comment by fiorenzino** [comment]
The 2 principal changes in my code:
1 - load file config using java Scanner instead of vertx.filesystem (because the vertx will start using the config.json options)
private Single<JsonObject> loadFileConfig(JsonObject config) {
        if (config != null) {
            return save(config);
        }
        String confArg = "conf/config.json";
        File file = new File(confArg);
        System.out.println(file.getAbsolutePath());
        try (Scanner scanner = new Scanner(new File(confArg)).useDelimiter("\\A")) {
            String sconf = scanner.next();
            try {
                return save(new JsonObject(sconf));
            } catch (DecodeException e) {
                log.error("Configuration file " + sconf + " does not contain a valid JSON object");
                // empty config
                return save(new JsonObject());
            }
        } catch (FileNotFoundException e) {
            return save(new JsonObject());
        }
    }

2 - init vertx using the file config.json translated in JsonObject:

private Single<JsonObject> initVertx(JsonObject config) {
        VertxOptions options;
        if (config != null) {
            options = new VertxOptions(config);
        } else {
            options = new VertxOptions();
        }
        options.setWarningExceptionTime(Long.MAX_VALUE);
        vertx = Vertx.vertx(options);
        AppGlobals.get().setVertx(vertx);
        return Single.just(config);
    }
The limit of this method is:
       vertx = Vertx.vertx(options);
If the options clustered=true, we need use:
AtomicReference<AsyncResult<Vertx>> result = new AtomicReference<>();
Vertx.clusteredVertx(options, ar -> {
  result.set(ar);
 });
vertx = Vertx.vertx(options);

The Starter (deprecated) or the Launcher, are the equivalent of our Server: 
they are the deployer of Verticles. In our case, we need only the code where they run the Vertx instance, using the configuration passed to the Server. 
The method complete, interesting for us is:
io.vertx.core.Starter.startVertx(boolean clustered, boolean ha, Args args)

Can you share your code formatter profile?
In some project i use https://github.com/forge/core/blob/master/eclipse-code-formatter-profile.xml

**Comment by FroMage** [comment]
I'm using the default Eclipse formatting: one tab per level.

**Comment by FroMage** [comment]
Closing as it is now supported, I also added some docs. Thanks a lot!
