### ISSUE TITLE
ClassNotFoundException DefaultExceptionHandler

### ISSUE THREAD

**Issue by fiorenzino** [FroMage/redpipe#13]
Starting the server i receive this error:

mar 23, 2018 12:43:14 AM org.jboss.resteasy.plugins.providers.RegisterBuiltin registerProviders
WARN: RESTEASY002120: ClassNotFoundException: Unable to load builtin provider net.redpipe.engine.resteasy.DefaultExceptionHandler from jar:file:/Users/fiorenzo/.m2/repository/net/redpipe/redpipe-engine/0.0.2-SNAPSHOT/redpipe-engine-0.0.2-SNAPSHOT.jar!/META-INF/services/javax.ws.rs.ext.Providers
java.lang.ClassNotFoundException: net.redpipe.engine.resteasy.DefaultExceptionHandler

**Comment by FroMage** [comment]
Ah, probably I forgot to push something, sorry.

**Comment by FroMage** [comment]
Should be fixed, thanks!
