### ISSUE TITLE
redpipe-router missing on Maven Repo

### ISSUE THREAD

**Issue by targeter21** [FroMage/redpipe#28]
Hi, I tried to start the hello-world example, but could not due to some dependency issues. I found that only `0.0.1` is uploaded to Maven Repo, not` 0.0.2-SNAPSHOT` like the POM is setup currently; changing the project version to `0.0.1` temporarily fixes the issue for all except one dependency. I also can't seem to find `redpipe-router` anywhere on Maven Repo and the `getURI()` function isn't available in other vert.x `Router` classes.

**Comment by FroMage** [comment]
Damn, you're right I must have forgotten to publish it. I'll try to fix this ASAP.

**Comment by FroMage** [comment]
Hi,

I just pushed version 0.0.2 which has the router module.

Cheers.
