### ISSUE TITLE
Bean registration warnings

### ISSUE THREAD

**Issue by coder123456** [FroMage/redpipe#31]
While starting up the server following warnings are logged

WARN: RESTEASY002155: Provider class net.redpipe.engine.resteasy.DefaultExceptionMapper is already registered.  2nd registration is being ignored.
May 18, 2018 9:03:06 AM org.jboss.resteasy.spi.ResteasyProviderFactory registerProvider
WARN: RESTEASY002155: Provider class net.redpipe.engine.resteasy.BufferBodyWriter is already registered.  2nd registration is being ignored.
May 18, 2018 9:03:06 AM org.jboss.resteasy.spi.ResteasyProviderFactory registerProvider
WARN: RESTEASY002155: Provider class net.redpipe.engine.rxjava.SingleProvider is already registered.  2nd registration is being ignored.
May 18, 2018 9:03:06 AM org.jboss.resteasy.spi.ResteasyProviderFactory registerProvider
WARN: RESTEASY002155: Provider class net.redpipe.engine.security.AuthorizationExceptionMapper is already registered.  2nd registration is being ignored.
May 18, 2018 9:03:06 AM org.jboss.resteasy.spi.ResteasyProviderFactory registerProvider
WARN: RESTEASY002155: Provider class net.redpipe.engine.template.TemplateResponseFilter is already registered.  2nd registration is being ignored.
May 18, 2018 9:03:06 AM org.jboss.resteasy.spi.ResteasyProviderFactory registerProvider
WARN: RESTEASY002155: Provider class net.redpipe.engine.security.AuthorizationFilterFeature is already registered.  2nd registration is being ignored.
May 18, 2018 9:03:06 AM org.jboss.resteasy.spi.ResteasyProviderFactory registerProvider
WARN: RESTEASY002155: Provider class net.redpipe.engine.resteasy.JsonObjectBodyReader is already registered.  2nd registration is being ignored.
May 18, 2018 9:03:06 AM org.jboss.resteasy.spi.ResteasyProviderFactory registerProvider
WARN: RESTEASY002155: Provider class net.redpipe.engine.rxjava.ObservableProvider is already registered.  2nd registration is being ignored.
May 18, 2018 9:03:06 AM org.jboss.resteasy.spi.ResteasyProviderFactory registerProvider
WARN: RESTEASY002155: Provider class net.redpipe.engine.security.AuthenticationExceptionMapper is already registered.  2nd registration is being ignored.
May 18, 2018 9:03:06 AM org.jboss.resteasy.spi.ResteasyProviderFactory registerProvider
WARN: RESTEASY002155: Provider class net.redpipe.engine.resteasy.RxVertxProvider is already registered.  2nd registration is being ignored.
May 18, 2018 9:03:06 AM org.jboss.resteasy.spi.ResteasyProviderFactory registerProvider
WARN: RESTEASY002155: Provider class net.redpipe.engine.resteasy.JsonObjectBodyWriter is already registered.  2nd registration is being ignored.

**Comment by FroMage** [comment]
How do you start the server?

**Comment by coder123456** [comment]
Using gradle and IDE

**Comment by FroMage** [comment]
OK thanks, I'll check that.

**Comment by FroMage** [comment]
OK, found it, thanks!
