### ISSUE TITLE
Add server host configuration option

### ISSUE THREAD

**Issue by aesteve** [FroMage/redpipe#35]
With Vert.x when creating an http server, there's a [host](https://vertx.io/docs/apidocs/io/vertx/core/http/HttpServerOptions.html#setHost-java.lang.String-) option.

It's not configurable in Redpipe (the port is). I'm a bit afraid it might cause some trouble in some corner cases like cloud deployment.

I think the only times I've been using it, was with Heroku / [OpenShift](https://github.com/vert-x3/vertx-openshift-diy-quickstart#step-2---application-preparation) deployment, where you're given a host to listen on, and just can't listen on "localhost" or "0.0.0.0".

Maybe make this a configurable option and expose it through `AppGlobals`

**Comment by FroMage** [comment]
Yeah, you're right it should be configurable. Probably via a config option like the port.

**Comment by FroMage** [comment]
Fixed.
