### ISSUE TITLE
eventbus - cdi events

### ISSUE THREAD

**Issue by fiorenzino** [FroMage/redpipe#8]
Should be really interesting the interaction CDI - vertx EventBus:

in the sender:
   @Inject
   Event<Message<AreaEvent>> eventService;
....
   eventService.fire(areaEvent);

in the receiver:
   public void onMessage(@Observes AreaEvent areaEvent) {

 }
 translated in vertx:
in the sender:
vertx.eventBus().publish("event-queue", new JsonObject().put("areaEvent", areaEvent));

in the receiver:
  EventBus eb = vertx.eventBus();
  eb.<String>consumer(DETECTIONS_QUEUE, this::consume);
    
protected void consume(Message<AreaEvent> message) {
  System.out.println(message.body())
}

what do you think about it?

**Comment by FroMage** [comment]
Isn't it the same as already provided by http://docs.jboss.org/weld/weld-vertx/latest/ ?

**Comment by fiorenzino** [comment]
ops.. you are right.. sorry!

**Comment by FroMage** [comment]
np :)
